"""
aqc/backtester/execution.py
===========================
Execution handler facade used by the backtest engine.

The :class:`ExecutionEngine` wraps the broker and maintains a mapping of
``symbol → latest MarketEvent`` so that the broker always has a current
price when filling orders.

Author: AQC Team
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Optional

from aqc.backtester.event import FillEvent, MarketEvent, OrderEvent
from aqc.backtester.broker import ExecutionHandler

if TYPE_CHECKING:
    from aqc.backtester.event_queue import EventQueue

logger = logging.getLogger(__name__)


class ExecutionEngine:
    """Thin facade over :class:`~aqc.backtester.broker.ExecutionHandler`.

    Maintains an internal cache of the most recent :class:`~aqc.backtester.event.MarketEvent`
    per symbol so that the broker has a reference price when an order arrives.

    Parameters
    ----------
    broker:
        The underlying execution handler (simulated or live).
    event_queue:
        Shared event queue (used for logging only; the broker enqueues fills).

    Examples
    --------
    >>> engine = ExecutionEngine(broker=SimulatedBroker(eq), event_queue=eq)
    >>> engine.on_market_event(market_event)  # updates price cache
    >>> engine.on_order_event(order_event)    # triggers broker fill
    """

    def __init__(
        self,
        broker: ExecutionHandler,
        event_queue: "EventQueue",
    ) -> None:
        self._broker = broker
        self._eq = event_queue
        self._latest_bars: dict[str, MarketEvent] = {}

    def on_market_event(self, event: MarketEvent) -> None:
        """Cache the latest bar so orders for this symbol can be filled.

        Parameters
        ----------
        event:
            Incoming market bar.
        """
        self._latest_bars[event.symbol] = event

    def on_order_event(self, event: OrderEvent) -> Optional[FillEvent]:
        """Forward an order to the broker for execution.

        Looks up the latest bar for *event.symbol* and passes it to the
        broker's :meth:`~aqc.backtester.broker.ExecutionHandler.execute_order`
        method.

        Parameters
        ----------
        event:
            Order to fill.

        Returns
        -------
        FillEvent | None
            The fill generated by the broker, or ``None`` if the order could
            not be filled.
        """
        latest_bar = self._latest_bars.get(event.symbol)
        if latest_bar is None:
            logger.error(
                "No market data for symbol '%s' — order %s cannot be filled.",
                event.symbol,
                event.event_id,
            )
            return None

        return self._broker.execute_order(event, market_event=latest_bar)

    def __repr__(self) -> str:
        return (
            f"ExecutionEngine(broker={self._broker!r}, "
            f"tracked_symbols={list(self._latest_bars.keys())})"
        )
