"""
aqc/backtester/portfolio.py
===========================
Portfolio engine for the AQC event-driven backtesting framework.

The portfolio is the central accounting authority of the system.  It:

1. Receives :class:`~aqc.backtester.event.SignalEvent` objects from strategies.
2. Translates signals into :class:`~aqc.backtester.event.OrderEvent` objects
   after consulting the :class:`~aqc.risk.risk_manager.RiskManager`.
3. Listens for :class:`~aqc.backtester.event.FillEvent` objects from the
   broker and updates internal position and PnL state accordingly.
4. Marks positions to market on every :class:`~aqc.backtester.event.MarketEvent`
   to compute unrealised PnL.

Design Principles
-----------------
* All state mutations go through well-defined methods — no external mutation.
* Position accounting uses a running *average cost* model for long positions
  and an analogous model for shorts.
* Equity curve is recorded at every bar for post-analysis.

Author: AQC Team
"""

from __future__ import annotations

import logging
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from aqc.backtester.event import (
    FillEvent,
    MarketEvent,
    OrderEvent,
    OrderSide,
    OrderType,
    SignalDirection,
    SignalEvent,
)

if TYPE_CHECKING:
    from aqc.backtester.event_queue import EventQueue
    from aqc.risk.risk_manager import RiskManager

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Position dataclass
# ---------------------------------------------------------------------------


@dataclass
class Position:
    """Represents an open position in a single instrument.

    Attributes
    ----------
    symbol:
        Instrument ticker.
    quantity:
        Signed quantity — positive for long, negative for short.
    avg_cost:
        Average entry price (cost basis per unit, always positive).
    realised_pnl:
        Cumulative realised PnL from *closed* trades on this symbol.
    unrealised_pnl:
        Unrealised PnL based on latest mark-to-market price.
    last_price:
        Most recently observed market price for this symbol.
    """

    symbol: str
    quantity: float = 0.0
    avg_cost: float = 0.0
    realised_pnl: float = 0.0
    unrealised_pnl: float = 0.0
    last_price: float = 0.0

    # ------------------------------------------------------------------
    # Derived metrics
    # ------------------------------------------------------------------

    @property
    def is_long(self) -> bool:
        """``True`` when the position is net long."""
        return self.quantity > 0

    @property
    def is_short(self) -> bool:
        """``True`` when the position is net short."""
        return self.quantity < 0

    @property
    def is_flat(self) -> bool:
        """``True`` when there is no open position."""
        return self.quantity == 0

    @property
    def market_value(self) -> float:
        """Current market value of the position (signed)."""
        return self.quantity * self.last_price

    @property
    def cost_basis(self) -> float:
        """Total cost basis of the position (unsigned)."""
        return abs(self.quantity) * self.avg_cost

    @property
    def total_pnl(self) -> float:
        """Realised + unrealised PnL."""
        return self.realised_pnl + self.unrealised_pnl

    # ------------------------------------------------------------------
    # Mutation helpers (called by Portfolio)
    # ------------------------------------------------------------------

    def mark_to_market(self, price: float) -> None:
        """Recalculate unrealised PnL given a new market price.

        Parameters
        ----------
        price:
            Current market price of the instrument.
        """
        self.last_price = price
        if not self.is_flat:
            self.unrealised_pnl = self.quantity * (price - self.avg_cost)
        else:
            self.unrealised_pnl = 0.0

    def apply_fill(self, side: OrderSide, qty: float, price: float) -> float:
        """Update position state after a fill.

        Uses an average-cost accounting model:

        * **Opening / Adding**: weighted average of existing cost and new fill.
        * **Reducing / Closing**: realise PnL proportional to shares closed.
        * **Reversing**: close entire existing position (realise PnL), then
          open a new position in the opposite direction.

        Parameters
        ----------
        side:
            Buy or sell.
        qty:
            Absolute quantity filled (always positive).
        price:
            Fill price.

        Returns
        -------
        float
            Realised PnL generated by this fill (0.0 if the fill only adds
            to an existing position in the same direction).
        """
        signed_qty = qty if side == OrderSide.BUY else -qty
        realised = 0.0

        if self.is_flat:
            # No existing position — just open
            self.quantity = signed_qty
            self.avg_cost = price

        elif (signed_qty > 0 and self.quantity > 0) or (signed_qty < 0 and self.quantity < 0):
            # Adding to an existing position (same direction) — update avg cost
            total_qty = abs(self.quantity) + abs(signed_qty)
            self.avg_cost = (
                abs(self.quantity) * self.avg_cost + abs(signed_qty) * price
            ) / total_qty
            self.quantity += signed_qty

        else:
            # Reducing or reversing
            closing_qty = min(abs(signed_qty), abs(self.quantity))
            pnl_per_unit = (price - self.avg_cost) if self.is_long else (self.avg_cost - price)
            realised = closing_qty * pnl_per_unit
            self.realised_pnl += realised

            remaining_signed = signed_qty + self.quantity  # net after close
            if abs(remaining_signed) < 1e-9:
                # Fully closed
                self.quantity = 0.0
                self.avg_cost = 0.0
            else:
                # Reversal: open new position in opposite direction
                self.quantity = remaining_signed
                self.avg_cost = price

        self.mark_to_market(price)
        return realised

    def __repr__(self) -> str:
        direction = "LONG" if self.is_long else ("SHORT" if self.is_short else "FLAT")
        return (
            f"Position({self.symbol} {direction} qty={self.quantity:.2f} "
            f"avg_cost={self.avg_cost:.4f} upnl={self.unrealised_pnl:.2f})"
        )


# ---------------------------------------------------------------------------
# EquitySnapshot dataclass
# ---------------------------------------------------------------------------


@dataclass
class EquitySnapshot:
    """A single point on the equity curve.

    Attributes
    ----------
    timestamp:
        Bar time of the snapshot.
    cash:
        Free cash at this point.
    equity:
        Total equity (cash + market value of all positions).
    total_pnl:
        Combined realised and unrealised PnL since inception.
    num_positions:
        Number of open positions.
    """

    timestamp: datetime
    cash: float
    equity: float
    total_pnl: float
    num_positions: int


# ---------------------------------------------------------------------------
# Portfolio
# ---------------------------------------------------------------------------


class Portfolio:
    """Tracks cash, positions, and PnL across the entire backtest.

    Parameters
    ----------
    event_queue:
        Shared event queue.  The portfolio writes :class:`~aqc.backtester.event.OrderEvent`
        objects onto this queue.
    risk_manager:
        Risk gate consulted before every order is submitted.
    initial_capital:
        Starting cash balance in the account currency.
    default_quantity:
        Default order size (number of units) when a strategy does not
        specify a quantity via signal strength.

    Examples
    --------
    >>> from aqc.backtester.event_queue import EventQueue
    >>> from aqc.risk.risk_manager import RiskManager
    >>> from aqc.backtester.portfolio import Portfolio
    >>> eq = EventQueue()
    >>> rm = RiskManager()
    >>> port = Portfolio(event_queue=eq, risk_manager=rm, initial_capital=100_000)
    >>> port.cash
    100000.0
    """

    def __init__(
        self,
        event_queue: "EventQueue",
        risk_manager: "RiskManager",
        initial_capital: float = 100_000.0,
        default_quantity: float = 100.0,
    ) -> None:
        self._eq = event_queue
        self._risk = risk_manager
        self.initial_capital = initial_capital
        self.cash = initial_capital
        self.default_quantity = default_quantity

        self.positions: dict[str, Position] = {}
        self.equity_curve: list[EquitySnapshot] = []
        self.trade_log: list[dict] = []

        self._total_commission: float = 0.0

    # ------------------------------------------------------------------
    # Event handlers
    # ------------------------------------------------------------------

    def on_market_event(self, event: MarketEvent) -> None:
        """Mark all positions to market using the latest close price.

        Parameters
        ----------
        event:
            The incoming market bar.
        """
        symbol = event.symbol
        price = event.close_price

        if symbol in self.positions:
            self.positions[symbol].mark_to_market(price)

        self._record_equity_snapshot(event.bar_time)

    def on_signal_event(self, event: SignalEvent) -> None:
        """Translate a signal into an order after risk validation.

        Parameters
        ----------
        event:
            Incoming signal from a strategy.
        """
        if event.direction == SignalDirection.HOLD:
            return

        quantity = self._size_order(event)
        if quantity <= 0:
            logger.debug(
                "Signal %s produced zero-size order — skipping", event.event_id
            )
            return

        side = self._signal_to_side(event)
        if side is None:
            return

        order = OrderEvent(
            symbol=event.symbol,
            order_type=OrderType.MARKET,
            side=side,
            quantity=quantity,
            strategy_id=event.strategy_id,
            signal_ref=event.event_id,
        )

        # Risk gate
        approved, reason = self._risk.validate_order(order, self)
        if not approved:
            logger.warning(
                "Order rejected by RiskManager: %s — reason: %s",
                order,
                reason,
            )
            return

        logger.info(
            "Order submitted: %s %s %.2f @ MARKET (signal_ref=%s)",
            order.side.value,
            order.symbol,
            order.quantity,
            event.event_id,
        )
        self._eq.put(order)

    def on_fill_event(self, event: FillEvent) -> None:
        """Update portfolio state after a fill is confirmed.

        Parameters
        ----------
        event:
            Confirmed fill from the broker.
        """
        symbol = event.symbol
        if symbol not in self.positions:
            self.positions[symbol] = Position(symbol=symbol)

        pos = self.positions[symbol]
        realised = pos.apply_fill(event.side, event.quantity, event.fill_price)

        # Update cash: BUY deducts cash; SELL adds cash; commission always deducted
        if event.side == OrderSide.BUY:
            self.cash -= event.quantity * event.fill_price + event.commission
        else:
            self.cash += event.quantity * event.fill_price - event.commission

        self._total_commission += event.commission

        self.trade_log.append(
            {
                "timestamp": event.timestamp,
                "symbol": symbol,
                "side": event.side.value,
                "quantity": event.quantity,
                "fill_price": event.fill_price,
                "commission": event.commission,
                "realised_pnl": realised,
                "strategy_id": event.strategy_id,
            }
        )

        logger.info(
            "Fill processed: %s %s %.2f @ %.4f  comm=%.4f  realised_pnl=%.2f",
            event.side.value,
            symbol,
            event.quantity,
            event.fill_price,
            event.commission,
            realised,
        )

        # Risk manager daily loss tracking
        self._risk.record_fill(event)

    # ------------------------------------------------------------------
    # Derived metrics
    # ------------------------------------------------------------------

    @property
    def market_value(self) -> float:
        """Sum of market values of all open positions."""
        return sum(pos.market_value for pos in self.positions.values())

    @property
    def equity(self) -> float:
        """Total account equity (cash + market value of positions)."""
        return self.cash + self.market_value

    @property
    def total_realised_pnl(self) -> float:
        """Cumulative realised PnL across all instruments."""
        return sum(pos.realised_pnl for pos in self.positions.values())

    @property
    def total_unrealised_pnl(self) -> float:
        """Current unrealised PnL across all open positions."""
        return sum(pos.unrealised_pnl for pos in self.positions.values())

    @property
    def total_pnl(self) -> float:
        """Combined realised + unrealised PnL."""
        return self.total_realised_pnl + self.total_unrealised_pnl

    @property
    def gross_exposure(self) -> float:
        """Total absolute market value of all positions."""
        return sum(abs(pos.market_value) for pos in self.positions.values())

    @property
    def net_exposure(self) -> float:
        """Net (signed) market value of all positions."""
        return sum(pos.market_value for pos in self.positions.values())

    @property
    def num_open_positions(self) -> int:
        """Count of positions with non-zero quantity."""
        return sum(1 for pos in self.positions.values() if not pos.is_flat)

    @property
    def total_commission_paid(self) -> float:
        """Total commission paid throughout the backtest."""
        return self._total_commission

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _size_order(self, signal: SignalEvent) -> float:
        """Determine order quantity from signal strength.

        Uses a proportional sizing model: ``quantity = default_quantity * |strength|``.
        Subclasses can override for Kelly, volatility-targeting, etc.

        Parameters
        ----------
        signal:
            The incoming signal event.

        Returns
        -------
        float
            Number of units to trade (always non-negative).
        """
        return max(0.0, round(self.default_quantity * abs(signal.strength), 4))

    @staticmethod
    def _signal_to_side(signal: SignalEvent) -> Optional[OrderSide]:
        """Map signal direction to order side.

        Parameters
        ----------
        signal:
            Incoming signal.

        Returns
        -------
        OrderSide | None
            ``BUY`` for LONG signals, ``SELL`` for SHORT and EXIT signals,
            ``None`` if direction is HOLD.
        """
        mapping: dict[SignalDirection, Optional[OrderSide]] = {
            SignalDirection.LONG: OrderSide.BUY,
            SignalDirection.SHORT: OrderSide.SELL,
            SignalDirection.EXIT: OrderSide.SELL,
            SignalDirection.HOLD: None,
        }
        return mapping.get(signal.direction)

    def _record_equity_snapshot(self, timestamp: datetime) -> None:
        """Append a new data point to the equity curve.

        Parameters
        ----------
        timestamp:
            Bar time for this snapshot.
        """
        self.equity_curve.append(
            EquitySnapshot(
                timestamp=timestamp,
                cash=self.cash,
                equity=self.equity,
                total_pnl=self.total_pnl,
                num_positions=self.num_open_positions,
            )
        )

    def summary(self) -> dict:
        """Return a high-level summary dictionary for reporting.

        Returns
        -------
        dict
            Keys: ``initial_capital``, ``final_equity``, ``total_pnl``,
            ``total_realised_pnl``, ``total_unrealised_pnl``,
            ``total_commission``, ``num_trades``, ``num_open_positions``,
            ``return_pct``.
        """
        return {
            "initial_capital": self.initial_capital,
            "final_equity": round(self.equity, 2),
            "total_pnl": round(self.total_pnl, 2),
            "total_realised_pnl": round(self.total_realised_pnl, 2),
            "total_unrealised_pnl": round(self.total_unrealised_pnl, 2),
            "total_commission": round(self._total_commission, 2),
            "num_trades": len(self.trade_log),
            "num_open_positions": self.num_open_positions,
            "return_pct": round(
                (self.equity - self.initial_capital) / self.initial_capital * 100, 4
            ),
        }

    def __repr__(self) -> str:
        return (
            f"Portfolio(equity={self.equity:.2f}, cash={self.cash:.2f}, "
            f"positions={self.num_open_positions}, pnl={self.total_pnl:.2f})"
        )
