"""
aqc/ensemble/dynamic_weighting.py
===================================
Adaptive weight engine for dynamic ensemble sizing.

Author: Saksham Mishra — AlgoQuant Club
"""

from __future__ import annotations

import logging

import pandas as pd
import numpy as np

logger = logging.getLogger(__name__)


class DynamicWeightEngine:
    """Computes time-varying weights for a portfolio of alphas.

    Uses a rolling window of recent performance (IC or returns) to 
    dynamically adjust weights, decaying underperforming alphas.

    Parameters
    ----------
    lookback:
        Number of bars to look back for performance.
    half_life:
        Exponential decay half-life for historical performance weighting.
    """

    def __init__(self, lookback: int = 100, half_life: int = 20) -> None:
        self.lookback = lookback
        self.half_life = half_life

    def compute_weights(self, signal_returns: pd.DataFrame) -> pd.Series:
        """Compute current weights based on rolling performance.

        Parameters
        ----------
        signal_returns:
            DataFrame of realized returns generated by each alpha's signals.
            Columns are alpha names, index is time.

        Returns
        -------
        pd.Series
            Weights for the next period, indexed by alpha name.
        """
        if len(signal_returns) == 0:
            return pd.Series(dtype=float)

        window = signal_returns.tail(self.lookback)
        
        # Exponentially weighted mean return per alpha
        ewm_rets = window.ewm(halflife=self.half_life).mean().iloc[-1]
        
        # Exponentially weighted volatility per alpha
        ewm_vol = window.ewm(halflife=self.half_life).std().iloc[-1]
        ewm_vol = ewm_vol.replace(0, 1e-6) # avoid div zero
        
        # Sharpe proxy
        sharpe_proxy = ewm_rets / ewm_vol
        
        # Set negative sharpe weights to 0 (don't bet on mean reversion of bad alphas here)
        weights = sharpe_proxy.clip(lower=0)
        
        total = weights.sum()
        if total > 0:
            weights = weights / total
        else:
            # If all are negative, equal weight (or could be 0)
            weights = pd.Series(1.0 / len(weights), index=weights.index)
            
        return weights

    def compute_rolling_weights(self, signal_returns: pd.DataFrame) -> pd.DataFrame:
        """Compute rolling weights over time for backtesting the ensemble.

        Returns
        -------
        pd.DataFrame
            Weights over time.
        """
        weights_history = []
        
        for i in range(len(signal_returns)):
            if i < 10: # Need min history
                w = pd.Series(1.0 / signal_returns.shape[1], index=signal_returns.columns)
            else:
                w = self.compute_weights(signal_returns.iloc[:i])
            weights_history.append(w)
            
        return pd.DataFrame(weights_history, index=signal_returns.index)
